### ISSUE TITLE
Allow to join a server via a custom url link, easy for embedding. E.g. iFrames.

### ISSUE THREAD

**Issue by msinfo32github** [paradust7/minetest-wasm#11]
Allow custom url integration to link directly to a server, easy for hosting your own server to share easily.

E.g.

https://minetest.dustlabs.io/mt/?address=IP&port=30000&account=USER&pass=PASSWORD

**Comment by TamaMcGlinn** [comment]
I just confirmed this already works, just not on minetest.dustlabs.io - I don't know why. If I compile minetest-wasm and host it myself using a python3 http.server, a link such as below only requires only one click on the Play button to connect, and static/launcher.js can be edited to remove that as well.

```
http://localhost:8060/index.html?address=your-land.de&port=30000&name=Tama&pass=mypassword&go
```

Thanks are due to @y5nw for help with the parameter names, in [this issue I opened on minetest](https://github.com/minetest/minetest/issues/13097#issuecomment-1367497386).

Recommend closure of this issue.
