### ISSUE TITLE
Private proxy

### ISSUE THREAD

**Issue by giangduong** [paradust7/minetest-wasm#20]
I do not want to use the proxy, running at wss://minetest.dustlabs.io/proxy. Can i deploy my own proxy?

**Comment by paradust7** [comment]
You could run your own proxy server, but you would need to write your own. The protocol is very simple, the proxy client is here:

https://github.com/paradust7/webshims/blob/main/src/emsocket/proxy.js

You can set the proxy server here:

https://github.com/paradust7/minetest-wasm/blob/e8f754e1c59517be978935935849be61352cfc40/static/launcher.js#L576

A node.js proxy server for private use would be relatively easy to make.

I cannot distribute my exact version, because it is strongly linked to my web serving architecture and security model.

**Comment by giangduong** [comment]
Thanks for your response and comments.

Most of my system users (they are k12 students) use Chromebook in classes. So web client is the best way for them to access system. I need minetest client running on web but not minetest server.

I have studied the proxy client and do not know how to implement the proxy server. Can you share a simple version of the proxy server? I think it should be ok if you remove all the parts that related to architecture and security model.

Anyway, thanks in advance.

**Comment by giangduong** [comment]
At the moment, all the proxies are down.

**Comment by MadKamel** [comment]
Can confirm all proxies have been down since 24 hours ago. As of this comment, they seem to be back up?

**Comment by benda95280** [comment]
Hello,
Is there any example of proxy available ? Would it be possible to release one ?

Thanks

**Comment by rudyruby** [comment]
Hi there, an example or some more details would be really great!

**Comment by paradust7** [comment]
I can produce a demonstration of a private proxy, but I need to understand everyone's use case. The proxy involves many things:

1) Handling secure websockets (requires an SSL certificate because of the extra security requirements for wasm apps)
2) Proxying requests for content to content.minetest.net
3) Proxying requests for the server list to servers.minetest.net
4) Proxying connections to regular minetest servers (server addresses) over UDP.
5) Creating virtual networks so that minetest web clients can connect together using a shared key

Which of these features do you need? What do you want to modify/change the behavior of? What would a minimal viable private proxy look like to you?

My initial assessment of these is:

(1) is part of the web serving architecture, and I would not be able to provide it out of the box. It would be up to you to configure the webserver correctly.

(2), (3), (4) I'd rather not ship, because they potentially expose minetest.net and minetest servers to flooding/DoS attack by misconfigured proxies.

(5) would be the easiest to do, as long as it is only one game/key at a time.

**Comment by rudyruby** [comment]
(5) would be the closest scenario for my use case. Thx!

**Comment by paradust7** [comment]
@rudyruby

I added a sample proxy that runs under node.js:

https://github.com/paradust7/minetest-wasm-sample-proxy

And I added multiplayer launch to the default page generated by minetest-wasm.
(commit 8a495e165d7c170838afead94153e26627dd0f28)

By default it uses the public proxies, but you can easily substitute your own private proxy.

**Comment by giangduong** [comment]
I need item #4.

**Comment by rudyruby** [comment]
@paradust7 Thanks for the sample proxy! Excellent!

I tried it out, but got stuck with the connection (https://github.com/paradust7/minetest-wasm-sample-proxy/issues/1)

**Comment by paradust7** [comment]
@rudyruby I just updated the sample proxy, and made a few touch-ups to index.html in minetest-wasm.

There's now a "DIRECT_PROXY" setting which you can modify in settings.js in the sample proxy. This sets up static routes which the proxy will honor.

You should be able to replace the 127.0.0.1 and 30000 with your own server's ip/port.

**Comment by paradust7** [comment]
@giangduong I believe this should also work for your case

**Comment by cygbs** [comment]
https://github.com/cygbs/Luanti-Tools/blob/main/WASM-PROXY/ws_proxy.patch

I'm trying to add support for the Minetest server itself. This patch should allow the server to provide its own proxy and inject it directly into the server's internal MTP stack.

It’s just like the server supports it natively, except that this proxy only allows clients to connect to that specific server.
